services:
  vrv-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vrv_group_website
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
